### ISSUE TITLE
[Bug]: Password list

### ISSUE THREAD

**Issue by oliver-oswald** [four-man-army/nextjs_password_safe#21]
### What happened?

When entering a new password the site crashes because it says it can't render objects. But when viewing the [last commit](https://github.com/four-man-army/nextjs_password_safe/tree/769e3db711b72ca819d7b98dbaeb1707c450a159) everything was fine. I have a suspicion it has something to do with the `map()` function called on list.

### Version

1.0.2 (Default)

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
Uncaught Error Error: Objects are not valid as a React child (found: object with keys {title, user, password}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:14887:1)
    at createChild (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:15139:1)
    at reconcileChildrenArray (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:15404:1)
    at reconcileChildFibers (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:15821:1)
    at reconcileChildren (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:19167:1)
    at updateFragment (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:19514:1)
    at beginWork (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:21640:1)
    at callCallback (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:4164:1)
    at invokeGuardedCallbackDev (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:4213:1)
    at invokeGuardedCallback (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:4277:1)
    at beginWork$1 (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:27451:1)
    at performUnitOfWork (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:26557:1)
    at workLoopSync (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:26466:1)
    at renderRootSync (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:26434:1)
    at performSyncWorkOnRoot (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:26085:1)
    at flushSyncCallbacks (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:12042:1)
    at eval (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:25651:1)
Uncaught Error Error: Objects are not valid as a React child (found: object with keys {title, user, password}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:14887:1)
    at createChild (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:15139:1)
    at reconcileChildrenArray (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:15404:1)
    at reconcileChildFibers (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:15821:1)
    at reconcileChildren (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:19167:1)
    at updateFragment (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:19514:1)
    at beginWork (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:21640:1)
    at callCallback (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:4164:1)
    at invokeGuardedCallbackDev (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:4213:1)
    at invokeGuardedCallback (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:4277:1)
    at beginWork$1 (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:27451:1)
    at performUnitOfWork (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:26557:1)
    at workLoopSync (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:26466:1)
    at renderRootSync (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:26434:1)
    at recoverFromConcurrentError (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:25850:1)
    at performSyncWorkOnRoot (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:26096:1)
    at flushSyncCallbacks (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:12042:1)
    at eval (c:\Users\olli0\Documents\programming\Schule\bbw\modul_183\passwordSafe\nextjs_password_safe\node_modules\react-dom\cjs\react-dom.development.js:25651:1)
The above error occurred in the <Fragment> component:

    at div
    at div
    at eval (webpack-internal:///./node_modules/antd/es/card/Card.js:55:62)
    at div
    at Item (webpack-internal:///./node_modules/antd/es/space/Item.js:15:24)
    at div
    at Space (webpack-internal:///./node_modules/antd/es/space/index.js:55:62)
    at div
    at Home (webpack-internal:///./pages/safe.tsx:28:91)
    at main
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:69:25)
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:52:66)
    at section
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:83:63)
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:52:66)
    at section
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:83:63)
    at eval (webpack-internal:///./node_modules/antd/es/layout/layout.js:52:66)
    at div
    at RootLayout (webpack-internal:///./pages/layout.tsx:31:11)
    at SessionProvider (webpack-internal:///./node_modules/next-auth/react/index.js:478:24)
    at App (webpack-internal:///./pages/_app.tsx:23:11)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:301:63)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:850:919)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:60:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:173:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:346:11)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oliver-oswald** [comment]
Just fixed the issue
